### PR TITLE
Closes #69 add time formats

### LINKED ISSUE #69: xportr_write error in valid format
Hi @bms63 

This is in the context for using these functions for Roche. I'm getting an error in the xportr_write step of my code:
image
 I dug deeper into the code and when it calls xpt_validate, there's an issue with the format assigned:
image

can the expected_formats be updated with permutations of timew?

### PR DESCRIPTION
**Pull request by zdz2101**
Per #69 , add user's requested time formats

### CODE REVIEW

**Review by elimillera — APPROVED** [review]

**Review by bms63 — COMMENTED** [review]
Do we need to take out the other time and date stuff?

**Comment by zdz2101** [comment]
> Do we need to take out the other time and date stuff?

From my understanding when you use a metacore object or a spec it'll look something like this:

image


where type we're checking for text/char/Char/Text, etc. and the date/time/datetime stuff is under formats?

**Comment by bms63** [comment]
I was referring to your other comment on date and time stuff from the recent PR.  I thought you spotted somethign that needed fixing??

**Comment by zdz2101** [comment]
> I was referring to your other comment on date and time stuff from the recent PR. I thought you spotted somethign that needed fixing??

Yes, went and made an additional commit

**Review by bms63 — APPROVED** [review]
Legend

**Pull request merged**
